######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 13 00:37:07 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtnotepad.cpp
